<?php
function dbtng_module_practice_entry_insert($entry) {
    $return_value = NULL;
    try {
        $return_value = db_insert('dbtng_example')
            ->fields($entry)
            ->execute();
    }
    catch (Exception $e) {
        drupal_set_message(t('db_insert failed. Message = %message, query= %query',
            array('%message' => $e->getMessage(), '%query' => $e->query_string)), 'error');
    }
    return $return_value;
}
