<?php
function dbtng_module_practice_entry_insert($entry) {
    $return_value = NULL;
    try {
        $return_value = db_insert('dbtng_example')
            ->fields($entry)
            ->execute();
    }
    catch (Exception $e) {
        drupal_set_message(t('db_insert failed. Message = %message, query= %query',
            array('%message' => $e->getMessage(), '%query' => $e->query_string)), 'error');
    }
    return $return_value;
}

function dbtng_module_practice_entry_update($entry) {
    try {
        // db_update()...->execute() returns the number of rows updated.
        $count = db_update('dbtng_example')
            ->fields($entry)
            ->condition('pid', $entry['pid'])
            ->execute();
    }
    catch (Exception $e) {
        drupal_set_message(t('db_update failed. Message = %message, query= %query',
            array('%message' => $e->getMessage(), '%query' => $e->query_string)), 'error');
    }
    return $count;
}

function dbtng_module_practice_entry_delete($entry) {
    db_delete('dbtng_example')
        ->condition('pid', $entry['pid'])
        ->execute();

}
function dbtng_module_practice_entry_load($entry = array()) {
    // Read all fields from the dbtng_example table.
    $select = db_select('dbtng_example', 'example');
    $select->fields('example');

    // Add each field and value as a condition to this query.
    foreach ($entry as $field => $value) {
        $select->condition($field, $value);
    }
    // Return the result in object format.
    return $select->execute()->fetchAll();
}

function dbtng_module_practice_advanced_list() {
    $output = '';

    $select = db_select('dbtng_example', 'e');

    $select->join('users', 'u', 'e.uid = u.uid');

    $select->addField('e', 'pid');
    $select->addField('u', 'name', 'username');
    $select->addField('e', 'name');
    $select->addField('e', 'surname');
    $select->addField('e', 'age');
    $select->condition('e.name', 'John');
    $select->condition('e.age', 18, '>');
    $select->range(0, 50);
    $entries = $select->execute()->fetchAll(PDO::FETCH_ASSOC);
    if (!empty($entries)) {
        $rows = array();
        foreach ($entries as $entry) {
            $rows[] = array_map('check_plain', $entry);
        }
        $header = array(t('Id'), t('Created by'), t('Name'), t('Surname'), t('Age'));
        $output .= theme('table', array('header' => $header, 'rows' => $rows));
    }
    else {
        drupal_set_message(t('No entries meet the filter criteria (Name = "John" and Age > 18).'));
    }
    return $output;
}
function dbtng_module_practice_help($path) {
    $output = '';
    switch ($path) {
        case 'examples/dbtng':
            $output = t('Generate a list of all entries in the database. There is no filter in the query.');
            break;

        case 'examples/dbtng/advanced':
            $output  = t('A more complex list of entries in the database.') . ' ';
            $output .= t('Only the entries with name = "John" and age older than 18 years are shown, the username of the person who created the entry is also shown.');
            break;

        case 'examples/dbtng/update':
            $output = t('Demonstrates a database update operation.');
            break;

        case 'examples/dbtng/add':
            $output = t('Add an entry to the dbtng_example table.');
            break;
    }
    return $output;
}
function dbtng_module_practice_menu(){
    $items = array();

    $items['examples/dbtng'] = array(
        'title' => 'DBTNG Example',
        'page callback' => 'dbtng_example_list',
        'access callback' => TRUE,
    );
    $items['examples/dbtng/list'] = array(
        'title' => 'List',
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => -10,
    );
    $items['examples/dbtng/add'] = array(
        'title' => 'Add entry',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dbtng_example_form_add'),
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
        'weight' => -9,
    );
    $items['examples/dbtng/update'] = array(
        'title' => 'Update entry',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dbtng_example_form_update'),
        'type' => MENU_LOCAL_TASK,
        'access callback' => TRUE,
        'weight' => -5,
    );
    $items['examples/dbtng/advanced'] = array(
        'title' => 'Advanced list',
        'page callback' => 'dbtng_example_advanced_list',
        'access callback' => TRUE,
        'type' => MENU_LOCAL_TASK,
    );

    return $items;
}