<?php

function dbtng_module_practice_install() {
  // Add a default entry.
  $fields = array(
    'name'    => 'John',
    'surname' => 'Doe',
    'age'     => 0,
  );
  db_insert('dbtng_module_practice')
    ->fields($fields)
    ->execute();

  // Add another entry.
  $fields = array(
    'name'    => 'John',
    'surname' => 'Roe',
    'age'     => 100,
    'uid'     => 1,
  );
  db_insert('dbtng_module_practice')
    ->fields($fields)
    ->execute();
}